# Generated by Django 5.1.1 on 2024-10-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration', models.BooleanField(default=False)),
                ('panel', models.BooleanField(default=False)),
                ('motor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink1', models.IntegerField(default=0)),
                ('drink2', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('info', models.IntegerField(default=0)),
                ('info2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(default=70)),
                ('time_wait', models.IntegerField(default=5)),
                ('laser_mode', models.IntegerField(default=2)),
                ('autovalue', models.BooleanField(default=True)),
                ('presence_cup', models.BooleanField(default=True)),
            ],
        ),
    ]
