# Generated by Django 5.1.1 on 2024-10-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_filler_info3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filler',
            name='info2',
        ),
    ]
