# Generated by Django 5.1.1 on 2024-10-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_filler_info2'),
    ]

    operations = [
        migrations.AddField(
            model_name='filler',
            name='info2',
            field=models.IntegerField(default=0),
        ),
    ]
