# Generated by Django 5.1.1 on 2024-10-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_filler_info2'),
    ]

    operations = [
        migrations.AddField(
            model_name='filler',
            name='pumping_ready',
            field=models.BooleanField(default=False),
        ),
    ]
